name: Build and Deploy Website
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Deploy
    steps:
      - uses: actions/setup-python@v3
        with:
          python-version: '3.x'
      - shell: bash
        run: pip3 install virtualenv
      - uses: actions/checkout@v2
        with:
          path: vercors-web
      - uses: actions/checkout@v2
        with:
          repository: utwente-fmt/vercors-web-build
          path: vercors-web-build
          token: ${{ secrets.VERCORS_BOT_PAT }}
      - shell: bash
        run: |
          pip3 install virtualenv
          cd vercors-web
          virtualenv venv -p python3
          source venv/bin/activate
          pip install -r requirements.txt
          python build.py
          cd ..
          rm -r vercors-web-build/pub/*
          cp -r vercors-web/build/* vercors-web-build/pub
          ls -l vercors/web-build/pub