name: Build and Deploy Website
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Deploy
    steps:
      - run: sudo apt install pandoc
      - uses: actions/setup-python@v3
        with:
          python-version: '3.x'
      - shell: bash
        run: pip3 install virtualenv
      - uses: actions/checkout@v2
        with:
          path: vercors-web
      - uses: actions/checkout@v2
        with:
          repository: utwente-fmt/vercors-web-build
          path: vercors-web-build
          token: ${{ secrets.VERCORS_BOT_PAT }}
      - run: |
          cd vercors-web
          virtualenv venv -p python3
          source venv/bin/activate
          pip install -r requirements.txt
          python build.py
      - run: rm -r vercors-web-build/pub/*
      - run: cp -r vercors-web/build/* vercors-web-build/pub
      - run: |
          cd vercors-web-build
          git add .
          git status
          git diff HEAD